### ISSUE TITLE
What is stops.txt?

### ISSUE THREAD

**Issue by kwkelly** [erikbern/mta#3]
Your plot_trips.py script attempts to open a file stops.txt. What is this file and where can I find it?

**Comment by kwkelly** [comment]
Never mind, the data appears to be from the MTA All Agency GTFS Schedule data for the New York City Transit Subway. 

Available here: http://web.mta.info/developers/data/nyct/subway/google_transit.zip

**Comment by erikbern** [comment]
thanks :)
